# Setting up needed packages and dependencies.

FROM jgoerzen/debian-base-security:bullseye
ENV TERM linux
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install python3-pip libpq-dev sudo faketime
RUN DEBIAN_FRONTEND=noninteractive apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /srv/market
COPY src/requirements.txt /srv/market
RUN pip3 install -r /srv/market/requirements.txt

COPY src/ /srv/market

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
