# Setting up needed packages and dependencies.

FROM jgoerzen/debian-base-security:bullseye
ENV TERM linux
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install python3-pip libpq-dev sudo faketime
RUN DEBIAN_FRONTEND=noninteractive apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip3 install waitress

COPY src/requirements.txt .
RUN pip3 install -r requirements.txt

COPY src/ .

CMD ["python3", "waitress_serve.py"]
